config/routes.rb
Rails.application.routes.draw do
  resources :gamers

  get '/play', to: 'roulettes#playManual', as: 'play'
  get '/reset', to: 'roulettes#reset', as: 'reset'

  root 'roulettes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gamer.rb
class Gamer < ApplicationRecord
end

app/models/roulette.rb
class Roulette < ApplicationRecord
  belongs_to :gamer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gamers_controller.rb
class GamersController < ApplicationController
  before_action :set_gamer, only: [:show, :edit, :update, :destroy]

  # GET /gamers
  # GET /gamers.json
  def index
    @gamers = Gamer.all
  end

  # GET /gamers/1
  # GET /gamers/1.json
  def show
  end

  # GET /gamers/new
  def new
    @gamer = Gamer.new
  end

  # GET /gamers/1/edit
  def edit
  end

  # POST /gamers
  # POST /gamers.json
  def create
    @gamer = Gamer.new(gamer_params)

    respond_to do |format|
      if @gamer.save
        format.html { redirect_to @gamer, notice: 'Gamer was successfully created.' }
        format.json { render :show, status: :created, location: @gamer }
      else
        format.html { render :new }
        format.json { render json: @gamer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gamers/1
  # PATCH/PUT /gamers/1.json
  def update
    respond_to do |format|
      if @gamer.update(gamer_params)
        format.html { redirect_to @gamer, notice: 'Gamer was successfully updated.' }
        format.json { render :show, status: :ok, location: @gamer }
      else
        format.html { render :edit }
        format.json { render json: @gamer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gamers/1
  # DELETE /gamers/1.json
  def destroy
    @gamer.destroy
    respond_to do |format|
      format.html { redirect_to gamers_url, notice: 'Gamer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gamer
      @gamer = Gamer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gamer_params
      params.require(:gamer).permit(:usuario, :saldo)
    end
end

app/controllers/roulettes_controller.rb
class RoulettesController < ApplicationController
    def index
        @roulettes = Roulette.all
    end

    def reset
      Roulette.delete_all
      redirect_to action: 'index'
    end

    def playManual
        @gamers = Gamer.all

        @gamers.each do |gamer|

            # Evalua las condiciones para la apuesta
            apuesta = apuesta(gamer.saldo, getTemperatura)
            gamer.update(saldo: gamer.saldo - apuesta)

            resultado = play(apuesta)
            puts '**Jugador: ' + gamer.inspect

            # Si lo apostado es igual a lo ganado, entonces perdio
            if resultado == apuesta
                Roulette.create(gamer: gamer, fecha: Date.current.to_s, apuesta: apuesta, resultado: 0)
            else
                Roulette.create(gamer: gamer, fecha: Date.current.to_s, apuesta: apuesta, resultado: 1)

                gamer.update(saldo: gamer.saldo + resultado)
            end
        end

        redirect_to action: 'index'
    end

    # Verifica si la temperatura de los proximos 7 dias es mayor a 32˚C
    def getTemperatura
        apikey = 'addcc19d518e0e9e0be78415f09bebb2'

        actual = Date.today

        for day in 0..7

            epoch = actual.to_time.to_i.to_s

            url = 'https://api.darksky.net/forecast/' + apikey + '/-33.4378,-70.6504,' + epoch

            darksky = JSON.parse(HTTP.get(url))

            temperatura = darksky['daily']['data'][0]['temperatureMax']
            # 32˚C son 89.6 ˚Fahrenheit
            return true if temperatura > 89.6

            actual += 1
        end

        false
    end

    def apuesta(dinero, temperatura)
        if dinero <= 1000 && dinero > 0
            dinero
        elsif temperatura
            dinero * rand(4..10) / 100
        elsif dinero > 1000
            dinero * rand(8..15) / 100
        end
    end

    def play(apuesta)
        probSeleccion = rand(100)
        probResultado = rand(100)

        # Probabilidad de que seleccione un color
        color = case probSeleccion
                when 0...49 then 'Rojo'
                when 49...98 then 'Negro'
                when 98...100 then 'Verde'
        end

        # Probabilidad de que salga ese color
        resultado = case probResultado
                    when 0...49 then 'Rojo'
                    when 49...98 then 'Negro'
                    when 98...100 then 'Verde'
        end

        # Si el color seleccionado con el resultado son iguales, gana
        if color === resultado
            return apuesta * 2 if resultado === 'Negro' || resultado === 'Rojo'

            return apuesta * 15 if resultado == 'Verde'

        else
            return apuesta
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gamers_helper.rb
module GamersHelper
end

app/helpers/roulettes_helper.rb
module RoulettesHelper
end

app/views/gamers/_form.html.erb
<%= form_for(gamer) do |f| %>
  <% if gamer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gamer.errors.count, "error") %> prohibited this gamer from being saved:</h2>

      <ul>
      <% gamer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario %>
    <%= f.text_field :usuario %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gamers/edit.html.erb
<h1>Editing Gamer</h1>

<%= render 'form', gamer: @gamer %>

<%= link_to 'Ver', @gamer %> |
<%= link_to 'Volver', gamers_path %>

app/views/gamers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gamers</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Saldo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gamers.each do |gamer| %>
      <tr>
        <td><%= gamer.usuario %></td>
        <td><%= gamer.saldo %></td>
        <td><%= link_to 'Jugar', gamer %></td>
        <td><%= link_to 'Ver', gamer %></td>
        <td><%= link_to 'Editar', edit_gamer_path(gamer) %></td>
        <td><%= link_to 'Eliminar', gamer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear nuevo jugador', new_gamer_path %>
<%= link_to 'Volver', root_path %>

app/views/gamers/new.html.erb
<h1>New Gamer</h1>

<%= render 'form', gamer: @gamer %>

<%= link_to 'Back', gamers_path %>

app/views/gamers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @gamer.usuario %>
</p>

<p>
  <strong>Saldo:</strong>
  <%= @gamer.saldo %>
</p>

<%= link_to 'Editar', edit_gamer_path(@gamer) %> |
<%= link_to 'Volver', gamers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimulacionRuleta</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/roulettes/index.html.erb
<h1>Partidas Jugadas</h1>

<%= button_to 'Administrar Jugadores',  gamers_path,:class => "button", :method => :get %>

<%= button_to 'A girar',  play_path, method: 'get' %>

<%= button_to 'Reset',  reset_path, method: 'get' %>

<table>
    <thead>
        <tr>
            <td>Jugador</td>
            <td>Fecha</td>
            <td>Apuesta</td>
            <td>Resultado</td>
        </tr>
    </thead>

    <tbody>
        <% @roulettes.each do |roulette| %>
        <tr>
          <td><%= roulette.gamer.usuario%></td>
          <td><%= roulette.fecha%></td>
          <td><%= roulette.apuesta%></td>
          <td><%= roulette.resultado%></td>
        </tr>
        <% end %>
    </tbody>
</table>